language: node_js
node_js:
  - "7"
install:
  - "npm install && bower install && mkdir build"
script:
  - "./scripts/deploy-demo src/styletransfer-demo.ts src/styletransfer-demo.html build"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
